### ISSUE TITLE
Dimension switching

### ISSUE THREAD

**Issue by suresttexas00** [benbaptist/minecraft-wrapper#107]
Is there a method for switching a player's dimension?

The idea is 
1) switch to the dimension of a player
2) TP to him.

without having to find a portal...

**Comment by benbaptist** [comment]
Unfortunately, I'm not sure how to implement this. Mojang is stupid for not having a command for teleporting across dimensions, or at least allowing the 'tp' command to do it - especially since spectator mod can teleport. 

I thought about a hack where maybe you can go into spectator mode and send a special packet to the server to force them to teleport regardless of dimension, and then putting them back into their original gamemode.

**Comment by suresttexas00** [comment]
The only way i have to do it now is create a portal at a known location (or set two portal blocks at a location near player, switch them to GM1, tp to the portal blocks, switch back to GM'x' and then tp to the final coords.... i actually think that sounds do-able.. :)

**Comment by suresttexas00** [comment]
well, it was not quite do-able after all.  I could create the portal blocks and tp the player to them, effect the inter-dimensional transport... and that's it.  I can't get wrapper/minecraft to wait until after the dimension change to 1) delete the portal blocks and 2) TP to the second player in that dimension.  I tried to slow it with a few methods:
- bulky multiple lines doing the same thing, hoping one of them catches.
- time.sleep(<seconds>) or using a loop and checking player.getdimension()... in either case, the program waits to teleport until after the loop/sleep, even if the teleport was effected BEFORE the loop started.... SO... YUCK!... All I have at this point is a couple commands to either /nether or /end.. the Mod/admin, must then TP after getting to the correct dimension... and they must run a separate command /clearp to get rid of the overworld portal that was used... again, even with those delays, the code would delete the portal before the player gets transferred.

**Comment by suresttexas00** [comment]
If this is hopeless, you can close if you want :(

**Comment by benbaptist** [comment]
A few things:
- Does the location of the portal really matter? You could make the portal static somewhere at spawn, or at least have an area dedicated to spawning portals and deleting them in the spawn chunks, so that they don't despawn and you can remove them.
- You could also cache the location of the portal that you made so that the next time that area is loaded/near that area, you can despawn it. Just check for player locations every once in a while, and if the coordinates of a player is somewhat close to the portal coordinates, then delete!

**Comment by suresttexas00** [comment]
Well, I went with the dedicated area for spawning them... there are two portals and I create them at y = 251 in the sky above the always-loaded spawn chunks.  The End portal is surrounded by bedrock to keep normal players out (TP is only way in), so I don't need to delete that one, since exiting the end is by death or winning.  The Nether can cause bigger problems because people can exit through that one.. and be in the sky 180 blocks up!  However, the bigger problem is that i cant do anything else.. like perform the desired tp to the target player.

**Comment by suresttexas00** [comment]
what would be the sort of code you would use to  do that periodic check to despawn the portals?

**Comment by benbaptist** [comment]
The easiest way to run code periodically for anything is to hook onto the
timer.second event. Then, just loop through self.minecraft.getPlayers() and
.getPosition() them and do the math to find whether or not they're in a
radius.

**Comment by suresttexas00** [comment]
How do you do that?  I don't really understand how, for instance, or WHY, this works like it does:

```	
	def onEnable(self):
		self.api.registerEvent("player.logout", self.playerLogout)

	def playerLogout(self, payload):
		pass
```
I don't see any such event "player.logout" on the [Event List](https://docs.google.com/spreadsheets/d/1TZ5fOiKBzzVVkCckP5RsjY1vjIuT41Ecxzem4jLBGCo/edit#gid=0)

**Comment by suresttexas00** [comment]
So I guess I am going to have to see if this will actually work:

```
	def onEnable(self):
		self.api.registerEvent("timer.second", self.timerSecond)
	def timerSecond(self, payload):
		"""Do something"""
```

**Comment by suresttexas00** [comment]
It works :D
