### ISSUE TITLE
1.9 Json changes - Be aware of this when creating plugins!

### ISSUE THREAD

**Issue by suresttexas00** [benbaptist/minecraft-wrapper#239]
https://bugs.mojang.com/browse/MC-83460

**Comment by benbaptist** [comment]
I don't think this will affect anything. I've already known about their broken-crap JSON and it previously had some serious problems with actual JSON - but that's the thing. Now they're moving to actual, proper JSON which means nothing for plugins since if we're using JSON.dumps(), we're already using the proper JSON that they enjoy. But yeah, if there were any instances in which we wrote our own JSON dumper that worked better with Minecraft 1.8 and earlier OR stripped all of the double-quotes, it would be screwed in 1.9.

**Comment by suresttexas00** [comment]
I affects commands you may write in a plugin like `self.api.minecraft.console("tellraw blah blah")

**Comment by benbaptist** [comment]
if you hardcode the actual JSON, it does indeed.

**Comment by suresttexas00** [comment]
SO can we use wrapper to correct the bad Json from the server to client in proxy mode?

**Comment by suresttexas00** [comment]
Well, the so called "bad JSON" I thought the 1.9 server was sending my clients may be a change in the disconnect packet...  This:
self.send(0x19, "json", ({"text": message, "color": "red"},))
Produces:
![image](https://cloud.githubusercontent.com/assets/10001762/10871592/265b8708-80b9-11e5-8a2f-05b07be61c6d.png)

but this:
self.send(0x19, "json", (message,))
produces:
![image](https://cloud.githubusercontent.com/assets/10001762/10871604/655b4114-80b9-11e5-9e73-d630b048262e.png)

**Comment by suresttexas00** [comment]
These disconnections were not actually the json itself... and they have been corrected (both on the mojang side and wrapper's.
