### ISSUE TITLE
how is the wrapper.py file encoded? (it is a compressed zip file)

### ISSUE THREAD

**Issue by CryptoCrafter** [benbaptist/minecraft-wrapper#250]
does anyone know the encodeing of wrapper.py??

if so plz help

**Comment by suresttexas00** [comment]
I answered from your other post.  Short answer: Some sort of zipped file.  Opens automatically with python2 (which is what wrapper is written in - not Py3 compatible).

**Comment by benbaptist** [comment]
Yup - Wrapper.py is indeed just a basic zip file with a .py extension. If you open it with a zip viewer, you'll be able to see all of the individual .py files. 

If you wish, you can instead download the 'src' folder and just run that instead, making it easier to modify the code. Auto-updating won't work, though.

**Comment by suresttexas00** [comment]
https://github.com/benbaptist/minecraft-wrapper

"""
Start Up

Run python Wrapper.py to start. On first start, it'll create a wrapper.properties file for you to configure and exit. Set it to boot the jar file of your choice, and then start Wrapper.py again.

Wrapper.py is a Python-executable zipped-up folder, rather than a plain text file. If you want to view the source code, open it with a zip file viewer OR download the src folder.
On first run, it'll create the configuration file 'wrapper.properties' and exit. Tune this file to your needs, and then run python Wrapper.py again.
"""
