### ISSUE TITLE
Can't backspace or use arrow keys in console

### ISSUE THREAD

**Issue by Darkness3840** [benbaptist/minecraft-wrapper#315]
For some reason, there is no colored output in the console, and I can not backspace or use the arrow keys to scroll between past commands/edit the current one.

**Comment by suresttexas00** [comment]
What version/branch are you using?

**Comment by suresttexas00** [comment]
also, what OS (linux/windows) are you using?

**Comment by Darkness3840** [comment]
I am using Centos 6 as my operating system, and the 0.7.6 release for the wrapper.

**Comment by suresttexas00** [comment]
The "master" branch is old, supports 1.8, and does not have any colorized text.  The two options for 1.9 -1.10 are "development" and "stable-formc1.9-1.10".  Development has the improvements like colorized console text.  If that version proves buggy, you can also use the "stable-formc..." which has many of the bugfixes and 1.9+ support backported.

**Comment by Darkness3840** [comment]
Thank you!

**Comment by suresttexas00** [comment]
and by buggy, I just meant if it lags really bad.  The stable-formc.** proxy runs faster for reasons I have not been able to determine.  The development branch has a whole new proxy package and lags on some systems.

**Comment by Darkness3840** [comment]
The development branch wrapper is giving me the following error: /usr/local/bin/python2.7: can't find '__main__' module in 'Wrapper.py'

**Comment by Darkness3840** [comment]
Along with the stable-formc

**Comment by suresttexas00** [comment]
what command are you using to run it?  Both of these __Do Not__ use the wrapper.py file.  you must run the source code folder directly.

**Comment by Darkness3840** [comment]
Oh, I did not know that. How exactly do I do that? The documentation on the branch pages does not say anything about that.

**Comment by suresttexas00** [comment]
i.e:
```python /home/Darkness/vanillaserver/wrapper```

Good point.  I thought it was in the wiki.

**Comment by Darkness3840** [comment]
So clone the entire repo folder, and run it as a whole?

**Comment by Darkness3840** [comment]
Err, the folder called wrapper.

**Comment by suresttexas00** [comment]
yea, you run the folder called wrapper.

**Comment by Darkness3840** [comment]
Alright. I really appreciate all your help.

**Comment by suresttexas00** [comment]
stableformc will _require_ that the wrapper folder be inside your minecraft server folder.  Development has a config item for running wrapper separately, but, for simplicity, I don't recommend it until you become very familiar with wrapper.

**Comment by Darkness3840** [comment]
Just to be clear: All I need to use the stableformc branch is the wrapper folder. Correct?

**Comment by suresttexas00** [comment]
yep.  In fact, you can do that for _all_ versions, even the original 0.7.6.

**Comment by Darkness3840** [comment]
Alright, i'll keep that in mind. I appreciate all the help man.

**Comment by suresttexas00** [comment]
You're welcome.  Sorry to say that development on this is presently stalled until after the new year (when I get more time off to work on it).  I really want to have the developement working as fast as the stable.  The dev is much better because it also has an entity tracking API and some other small improvements to the ban system, etc.

**Comment by Darkness3840** [comment]
That's understandable. Everyone has personal lives outside of development. Although, I may be able to learn python withing this year, and may be able to help out a bit on the development here in the future. I surely hope that I can help in any way.

**Comment by Darkness3840** [comment]
It doesn't seem like the stableformc is giving colored output. Beyond that, I can't backspace or use arrows keys still. Sorry for all the hasstle

**Comment by Darkness3840** [comment]
I think that being unable to backspace could be that I am using spongepowered (spongeforge). I have reason to believe that spongepowered will be the most used server modding API within the next year or so, and that you guys should roll out full compatibility for it. Again, I appreciate all the clarifications and help.

**Comment by Darkness3840** [comment]
Also, I'm sorry to bother again, but it doesn't seem like I can execute the dev branch using the folder. 

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/modded/AllTheMods/wrapper/__main__.py", line 5, in <module>
    from core.wrapper import Wrapper
  File "wrapper/core/wrapper.py", line 15, in <module>
    import proxy.base as proxy
  File "wrapper/proxy/base.py", line 8, in <module>
    import utils.encryption as encryption
  File "wrapper/utils/encryption.py", line 14, in <module>
    from Crypto.PublicKey import RSA
ImportError: No module named Crypto.PublicKey

**Comment by Darkness3840** [comment]
I figured out the issue. The problem was that in Centos 6, one has to go through many complications to use python2.7 with pip and such, hence why the dependencies were not downloading and installing properly. However, the development wrapper only outputs color for the wrapper's commands, and not for the commands from sponge. Is that supposed to happen?

**Comment by suresttexas00** [comment]
1) yes, wrapper only colorizes it's own output, not the subject server (how would it know what colors to use for another programs output??)
2) wrapper (in proxy mode, anyway) was not designed to be used WITH other modding platforms but as an alternative to them.  However, in non-proxy mode, it should support any server (and any minecraft version)... more on that in another comment.
3) It's been some 6 months since I looked into the ban code.  have you tried "/ban" and just plain "ban"?  I am not sure, but one or the other may pass the command to the server.  Also try /help from console.  I think there may be some explanation there on how to pass the same commands strictly to the server...

I will comment separately on each of these points more in separate replies... As you develop new issues, please bring them up in separate issue threads... this one has gone way off topic with new problems.

**Comment by suresttexas00** [comment]
Bans:  If you are using proxy mode you ___will___ want to let wrapper handle bans.  That is because the server (which should be in offline mode when the wrapper is in proxy mode) will be handling bans based on user name.  Only the wrapper will know the proper mojang id to ban.  If you let  the server take care of bans, a user can sidestep your ban with a name change.

**Comment by suresttexas00** [comment]
If you are using proxy mode, I have to ask "why".  Proxy mode exists primarily to implement mod-like plugins for vanilla servers.  The mod already has an API for creating plugins.. why use proxy?

If you are not using proxy, please tell me in some detail what features you are looking for in wrapper?  This is a weak area for me because I came to wrapper as a vanilla server user and I primarily have focused on proxy operation in my development activities. Therefore, I am lacking in the perspective of what the modding community is looking for from wrapper.

**Comment by suresttexas00** [comment]
regarding arrow keys... 
If you are talking about accessing a command history (up and down arrow), wrapper does not support a command history.
If you are talking about left-right for edits, I am not sure.  The console can get a bit buggy sometimes,especially after you do something it does not like... I have always called this "losing control of the console" and I have seen in happen in bukkit too.  It may be a problem that varies by operating system... Don't really know.

**Comment by suresttexas00** [comment]
Please keep this open (It brinks up a number of documentation issues that will need to be addressed).

**Comment by Darkness3840** [comment]
Ah, okay. I will make a separate issue for what I would ideally have in wrapper.

**Comment by suresttexas00** [comment]
I am also interested in getting your input on wrapper use cases (as regards modding platform uses).  We have a few different people using bukkit, forge, and (now) spongeforge.

**Comment by suresttexas00** [comment]
:) fixed #324
