### ISSUE TITLE
Missing documentation for events "player.dig" and "player.place"

### ISSUE THREAD

**Issue by Katipo007** [benbaptist/minecraft-wrapper#460]
Missing documentation for events "player.dig" and "player.place" in
`minecraft-wrapper/documentation/events.rst`

I can fill this in but I was unable to locate the origin of these events.

Another note is the event "player.achievement" is no longer used past 1.12 and should get a "player.advancement" equivalent (due to replacement of achievements with advancements)

Edit:
From observation, the payload of "player.dig" contains:
- playername - string, name of the player
- position - tuple, position of the block being broken
- player - api.player.Player object
- action - string, observed to be either 'begin_break' or 'end_break'
- face - int, block face id of the face being broken

Edit Two:
Found origin of "player.dig" & "player.place" in
`minecraft-wrapper/wrapper/proxy/client/parse_sb.py`
Also found some other events missing from documentation in 
`minecraft-wrapper/wrapper/proxy/server/parse_cb.py`
&
`minecraft-wrapper/wrapper/proxy/client/parse_sb.py`

Made a fork and will propose a file-change soon with the missing events added

**Comment by Katipo007** [comment]
#461

**Comment by suresttexas00** [comment]
This pull won't work because the documentation is generated automatically from the code and not from manual edits of the rst files.  I'm going to be busy for quite a bit, but I will keep this issue open.  The *.rst files are generated from doc strings in the code and compiled at build time from the build_script.py. 

The documentation generator is not bug free or complete yet.  I don't have all the events and some duplications do occur for different payload types.

Any pull request should change the doc strings located in the (for instance) `parse_cb.py` files, etc.  You may test for a successful build of rst files using build_script.py, _but do not pull any changes from the build_ (such as the actual rst files, Wrapper.py archive, md5 files, etc)

**Comment by suresttexas00** [comment]
I get back to achievements/advancements some other time.  I am not really certain it is useful as an event or whether the difference between the two is simple nomenclature or actual functionality.

As for the other events, they are now fixed.  I will pull the fix shortly.

**Comment by suresttexas00** [comment]
pulled fix.
