### ISSUE TITLE
/help

### ISSUE THREAD

**Issue by suresttexas00** [benbaptist/minecraft-wrapper#58]
Is there a way to intercept the Minecraft command help (I assume register indentical self.api.registerCommand("help", self._myroutine) )... 
but then do somthing like:

	def _help(self, player, args):
		player.message("\simple help - get help with simple plugin (home/spawn/etc)")
		self.minecraft.#make minecraft print rest of default help#

or

	def _help(self, player, args):
		#code to decide if they already passed an argmument like "simple" or "mc"
		#IF they did mc, then print out the default MC help function
		#If they did simple, then print my menu

		#make the menu display this if there were no args (val==0)
		player.message("\help simple - get help with simple plugin (home/spawn/etc)")
		player.message("\help mc - get help with minecraft commands (tell/me/etc)")
		self.minecraft.#make minecraft print rest of default help#

**Comment by benbaptist** [comment]
I've been thinking about it a bit, and wondered if this would be a good system.

Essentially, Wrapper.py is going to replace the vanilla help command with its own. The /help command with no parameters will just display a list of plugins/groups to choose from, one of them always being "vanilla" for all of the vanilla commands. When you do /help [group], it shows a list of the commands for that particular group, probably showing 6 commands per page or so. Doing /help [group] [page] (e.g. /help vanilla 2) will show that particular page. Also, just for the sake of taking advantage of tellraw's "clickEvent", I might have Previous and Next buttons that you can actually click within chat. Also, vanilla's help command will actually just send the 'help' command to the server, so if Minecraft is updated and new commands are added, it'll remain up-to-date and I won't have to maintain adding new commands.

As for registering help, I'm not 100% sure how this may go down. Perhaps an additional argument in .registerCommand(), such as this:

`self.api.registerCommand("pizza", self._pizza, help="The pizza command allows you to eat a pizza.")`

or with its own method, along these lines:

`self.api.registerHelp("pizza", "The pizza command allows you to eat a pizza.")`

I also wondered how you'd be able to specify the help group name in `help`. Perhaps at the top of the file, you could specify something like this:
`HELP = "PizzaCommands"`
which would be the name that users type in to see commands for that particular plugin. I haven't thought that all the way through yet, though.

I also figured that some people probably would want to print their own custom text or formatting when running the help command for their particular plugin, so I figured you could implement a __help__(self, player, page) into your plugin's Main class which will override the default help page. This won't override the entire 'help' command, just the one for your plugin, e.g. `/help PizzaCommands`. 

All of this is still just theoretical, as I haven't implemented any of this yet. 

Also, I've implemented the method player.execute(command) to aid in this - with proxy mode enabled, player.execute() will run the command as that player and will actually print the command output in their chat and everything (only works with vanilla commands, since it just sends it straight to the server itself). e.g. player.execute("help") will actually show the vanilla help in their chat.

**Comment by suresttexas00** [comment]
I could use this part:
Also, I've implemented the method player.execute(command) to aid in this - with proxy mode enabled, player.execute() will run the command as that player and will actually print the command output in their chat and everything (only works with vanilla commands, since it just sends it straight to the server itself). e.g. player.execute("help") will actually show the vanilla help in their chat.

I could then just take over the /help command and have "minecraft" as one of the items:
/help simple = help with this plugin
/help minecraft - minecraft command
/help otherplugin - etc


then run player.execute("help")

?

**Comment by benbaptist** [comment]
Yup! And make sure to pass the page number to the 'help' command, so you
can see all of the pages.

On Sun, Jan 11, 2015 at 7:09 PM, Surest Texas <notifications@github.com>
wrote:

> I could use this part:
> Also, I've implemented the method player.execute(command) to aid in this -
> with proxy mode enabled, player.execute() will run the command as that
> player and will actually print the command output in their chat and
> everything (only works with vanilla commands, since it just sends it
> straight to the server itself). e.g. player.execute("help") will actually
> show the vanilla help in their chat.
>
> I could then just take over the /help command and have "minecraft" as one
> of the items:
> /help simple = help with this plugin
> /help minecraft - minecraft command
> /help otherplugin - etc
>
> then run player.execute("help")
>
> ?
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/benbaptist/minecraft-wrapper/issues/58#issuecomment-69519003>
> .
>



-- 
http://sawmaster2.no-ip.org:82/

iPod network
