### ISSUE TITLE
python ? - "__init__"

### ISSUE THREAD

**Issue by suresttexas00** [benbaptist/minecraft-wrapper#60]
What does def __init__(self, api, log) do?  What has to be in this definition?  specifically, in the plugin code..

Like the essentials example, the __init__ is:
def __init__(self, api, log):
		self.api = api
		self.minecraft = api.minecraft
		self.log = log
		self.powertool = []

yet the code also uses the player.<methods>.. if they dont need a self.player= api.player, why is the self.minecraft = api.minecraft there?

**Comment by benbaptist** [comment]
The self.minecraft is only an optional shortcut, since I know I'll be using
it a lot. Otherwise, you can make as many shortcuts to methods or classes
as you'd like in your __init__ function. It's all just a matter of
speed/opinion, pretty much. :P

**Comment by suresttexas00** [comment]
what is required to be in init.... what if it is not there, what happens?

how is it a shortcut?  I notice that you dont need to "api.player.<function> even thought it was not in the __init__.  what special function does  making it a self.* do?   How come I can player.* without a .self.player = api.player?

I guess I also don't entirely get what __init__ does in python.. Is it a reserved name of some kind, or just a "convention" that everyone uses?

**Comment by suresttexas00** [comment]
It seems these "optional" shortcuts are the only thing inside the __init__, which is why I am wondering what it is for...

**Comment by benbaptist** [comment]
__init__ in Python is how classes work in Python. When you create a class, and you pass arguments to it, the first function that's executed is __init__. 

In reality, what's required in the __init__ function is purely up to what you're writing. In this case, I've made the two arguments 'api' and 'log'. The reason I pass the api class instead of just letting you import it is so that you're using your own personal instance of the API, and that it's easier to track which plugin is running what function, etc.

In reality, you could have nothing inside of a __init__ (aside from taking the arguments self, api, and log), and it'll just mean you won't be able to really do anything. 

TL,DR: __init__ is the first thing that's called when creating your plugin's class. It's nothing specific to Wrapper.py or a convention, but it's built into Python itself.

Also, dang Github for making it bold when I type __init__. :P

**Comment by suresttexas00** [comment]
"Also, dang Github for making it bold when I type init. :P"  

Yea, that is annoying

so should i be 
self.<api> = api.<api>  for  all the portions I use?

**Comment by benbaptist** [comment]
Yup. Like I said, it's only a shortcut, and 100% optional. But at least define self.api and self.log so you have access to those two.
