### ISSUE TITLE
Most of the player events are broken?

### ISSUE THREAD

**Issue by TomSharratt** [benbaptist/minecraft-wrapper#69]
I can't seem to get player.dig, player.place, player.move, player.interact to work.

**Comment by benbaptist** [comment]
Are you using proxy mode? Those events require that you basically filter
all SMP packets through Wrapper.py itself. Turn on proxy mode in
wrapper.properties, change the server port in server.properties to
something else and make sure online-mode is off. I also recommend turning
network compression off while using Wrapper.py's proxy mode since it'll do
the compression for you. Then, back in wrapper.properties, make sure
server-port is set to server.properties's port, and proxy-port to the port
that you would like people to connect to.

Of course, if you're doing all this and events aren't working, then
something far weirder is happening.

**Comment by TomSharratt** [comment]
Yep that fixed it. I'm not sure if I missed the documentation about that but thank you.
