### ISSUE TITLE
Error on leaving server.

### ISSUE THREAD

**Issue by TomSharratt** [benbaptist/minecraft-wrapper#70]
I get this error when someone leaves the server.

Last packet IDs (Server->Client) before disconnection:
[('0x15', 7), ('0x15', 7), ('0x12', 8), ('0x1c', 6), ('0x1a', 6), ('0x1c', 6), ('0x12', 8), ('0x15', 6), ('0x12', 8), ('0x18', 17)]
Failed to grab packet (SERVER)
Traceback (most recent call last):
  File "Wrapper.py/proxy.py", line 757, in handle
    id, original = self.packet.grabPacket()
  File "Wrapper.py/proxy.py", line 819, in grabPacket
    payload = self.recv(length)
  File "Wrapper.py/proxy.py", line 987, in recv
    d = self.socket.recv(length)
  File "/usr/lib/python2.7/socket.py", line 170, in _dummy
    raise error(EBADF, 'Bad file descriptor')
error: [Errno 9] Bad file descriptor

Last packet IDs (Server->Client) before disconnection:
[('0x15', 7), ('0x15', 7), ('0x12', 8), ('0x1c', 6), ('0x1a', 6), ('0x1c', 6), ('0x12', 8), ('0x15', 6), ('0x12', 8), ('0x18', 17)]

**Comment by benbaptist** [comment]
Don't worry about that - if you turned debug mode on, leaving the server
tends to be a lot more verbose, including printing tracebacks of things
that don't matter. That's normal since they disconnected, so the socket is
broken and an exception is raised. Eventually I'd like to clean up the
debug proxy stuff since it can be a tad overwhelming when debug mode is
turned on. :P
