### ISSUE TITLE
player.dig, player.place not updating when canceled

### ISSUE THREAD

**Issue by saltstorm** [benbaptist/minecraft-wrapper#71]
If I `return False` on either of these events the client doesn't get the memo and still breaks or places the block, but because it is client side and not server side it is causing them to think they broke/placed a block when they didn't (doesn't show for others and is really glitchy when walked into/on).

Any fix for this? It is like the client isn't getting the update.

**Comment by overjt** [comment]
I just test this in the development version and it works fine

**Comment by TomSharratt** [comment]
In version #69? I just tested and I'm still getting the bug, what is your config setup?

**Comment by benbaptist** [comment]
The problem is that I need to explicitly send a block packet back to the client telling it that the block was never placed, or broken. Placed is usually easy - most of the time, I just send an air block where they placed so it disappears instantly. However, breaking is not so easy because I need to know what the block was originally in order to send the packet back to the client telling it that the block wasn't broken. All I need to do is finish the code for receiving chunk data and small block updates in the connection, and then I can implement things like this. It'll also help for detecting the ID and damage value of the block that they broke, and such.

**Comment by suresttexas00** [comment]
where are these build numbers coming from?  I am showing #74 is the most recent build...

I noticed this same behavior, but I have not verified it under #74

**Comment by benbaptist** [comment]
I assume build #75 was probably a typo/mistake. I think #74 is still the most recent - but I'm going to be pushing more code soon.

**Comment by suresttexas00** [comment]
Well, i was not so sure, since the stable build happens to be number ##6#5

**Comment by benbaptist** [comment]
Oh, perhaps Tom meant to type #65 over #75. Although #75 is an actual build now - I just pushed it and it includes its own /help command and APIs for it.
