### ISSUE TITLE
player.connect

### ISSUE THREAD

**Issue by saltstorm** [benbaptist/minecraft-wrapper#74]
Struggling to get my setup working.

I want 2 servers both running on the Wrapper.py which I can teleport between using player.connect

At the moment i've got 2 proxies (25591, 25592) and two servers (25571, 25572) respectively. Offline mode is false in server.properties but true in the wrapper.properties and I get this error on connection:

![](http://puu.sh/eGvMJ/2b62bb92a7.png)

**Comment by TomSharratt** [comment]
It works when the proxies are set to online-mode=false but that obviously isn't what I want.

**Comment by TomSharratt** [comment]
From looking at the source code I think the issue is when connecting the person to the server it isn't doing any authentication/login, it just tries and puts the player on the server.

What could I do to fix this while your wrapper doesn't support it?

**Comment by benbaptist** [comment]
Make sure that the online-mode setting in wrapper.properties on the second wrapper instance (the one you're trying to connect to) is set to False as well. Since player.connect() requires the destination to be in offline (including wrapper's own proxy), it has to do that. 

At some point, I'd like to try to figure out some sort of authentication scheme between two Wrapper.py instances to make it a bit easier, but for now, the second wrapper.py has to be in offline mod as well (so make sure it cannot be connected to publically).

**Comment by TomSharratt** [comment]
So if I want to be able to connext people back or forth between the 2 servers would they both need to be in offline mode?

**Comment by benbaptist** [comment]
If you want to do player.connect() on both servers, yes. However, on the destination server, you can just kick the user and that'll send them back to the original server. Only the destination servers need to be in offline mode.
