### ISSUE TITLE
Readline does not work in Windows

### ISSUE THREAD

**Issue by suresttexas00** [benbaptist/minecraft-wrapper#95]
```
# I'm not 100% sure if readline works under Windows or not
try: import readline
except: pass
```

No, it does not indeed.. What is this used for?  Can it simply be omitted?

**Comment by benbaptist** [comment]
Wait, are you actually having a problem with it under Windows? It shouldn't be an issue, because if it fails to import or something, it just catches the error and moves on. It's so that you can use the arrow keys while typing into the console. It is useful on Linux systems, but if it fails on Windows, I'm not sure what else I can do. But it's not really that crazy of a feature, but useful to have.

**Comment by suresttexas00** [comment]
where else is it used?  Something for a future release?

Visual studio fails to resolve the reference, meaning it is not functional under my platform. I can't see it is doing anything and your note seemed to question it.  The code in question does not produce an actual error or anything.  It just seems un-needed or experimental.

**Comment by suresttexas00** [comment]
yea, you can't use arrow keys in the windows console. (.)

**Comment by benbaptist** [comment]
It isn't experimental - just not Windows compatible. It is there pretty much for Linux and other POSIX-like systems only. All that is needed is the import - it handles the rest on its own.
